# Site settings
title: Jordan Simpson | Frontend Developer and Web Designer
description: Jordan Simpson is a Frontend Developer and Web Designer based in Redditch.
baseurl: ""
url: "http://jordansimpson.co.uk"

# Build settings
markdown: kramdown
exclude: [node_modules]
